name: Spoolman
description: Manage your 3D printer filament with Spoolman on Home Assistant and keep track of your spools effortlessly
version: "1.0.0"
webui: http://[HOST]:[PORT:7912]
url: https://github.com/Jpwaters09/Home-Assistant-Addons/tree/main/Spoolman/
maintainer: Jacob Waters

slug: spoolman
startup: services
boot: auto

ports:
  "8000": "7912"

map:
  - share:rw

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386